import axios from 'axios';

const apiClient = axios.create({
  baseURL: import.meta.env.VITE_API_BASE_URL || 'https://localhost:8081',
  timeout: 15000,
  headers: {
    'Content-Type': 'application/json',
  },
});

export const setAuthToken = (token) => {
  if (token) {
    apiClient.defaults.headers.common['Authorization'] = `Bearer ${token}`;
  } else {
    delete apiClient.defaults.headers.common['Authorization'];
  }
};

// Initialize token from localStorage on app load
const initialToken = localStorage.getItem('token');
if (initialToken) {
  setAuthToken(initialToken);
}

// Map to track active host re-authentication promises
const refreshingHosts = new Map();

// Helper to determine if a URL belongs to a specific host
const getHostUidFromUrl = (url) => {
  if (!url) return null;
  // URLs usually follow pattern /UID/endpoint
  const cleanUrl = url.replace(/^\//, '');
  const segments = cleanUrl.split('/');
  let hostUid = segments[0];

  // If URL is /host/UID/..., the UID is the second segment
  if (hostUid === 'host' && segments[1]) {
    hostUid = segments[1];
  }

  // Simple heuristic: host UIDs are usually long strings (UUID-like) or specific identifiers
  return (hostUid && hostUid.length > 15) ? hostUid : null;
};

// Response interceptor
apiClient.interceptors.response.use(
  (response) => {
    // Standard unwrap logic: if backend returned { data: ..., note: ... }, extract data
    // If data is false or null, we still return the full response object to avoid falsy unwrap bugs
    // or we check strictly for property existence.
    const rawData = response.data;
    if (rawData && typeof rawData === 'object' && Object.prototype.hasOwnProperty.call(rawData, 'data')) {
      if (rawData.data === false || rawData.data === null || rawData.data === 0) {
        // If data is explicitly false/null, return the whole object so callers like hostSlice 
        // can check response.data === false reliably.
        return rawData;
      }
      return rawData.data;
    }
    return rawData;
  },
  async (error) => {
    const originalRequest = error.config;
    const apiData = error.response?.data;
    const statusCode = error.response?.status;

    // Handle 401 Unauthorized
    if (statusCode === 401 && !originalRequest._retry) {
      const hostUid = getHostUidFromUrl(originalRequest.url);
      const isLoginRequest = originalRequest.url?.includes('/cms-auth/login');

      if (hostUid) {
        // SCENARIO: Host-level 401

        if (isLoginRequest) {
          // 401 during a host login attempt -> System session itself is expired
          // "if revoke host login failed 401-> then it is consider as system login is expired. so do a logout operation."
          console.error('Host authentication failed with 401. Main system session has expired.');
          localStorage.removeItem('token');
          window.location.href = '/login';
          return Promise.reject(error);
        }

        // Standard host request failed with 401 -> Attempt re-authentication
        console.warn(`Host session for ${hostUid} expired. Initiating revocation and re-login...`);

        try {
          const { store } = await import('../app/store');
          const { revokeHostLogin, loginToHost } = await import('../features/host/hostSlice');

          // 1. "it should revoke host login"
          store.dispatch(revokeHostLogin(hostUid));

          // 2. "wait for result"
          if (!refreshingHosts.has(hostUid)) {
            const refreshPromise = store.dispatch(loginToHost(hostUid)).unwrap();
            refreshingHosts.set(hostUid, refreshPromise);
          }

          await refreshingHosts.get(hostUid);
          refreshingHosts.delete(hostUid);

          // 3. "proceed those request again"
          originalRequest._retry = true;
          // Ensure we use current headers (though token shouldn't have changed)
          return apiClient(originalRequest);
        } catch (refreshError) {
          refreshingHosts.delete(hostUid);

          // Note: If refreshError was a 401, it was already handled by the isLoginRequest check above 
          // for the secondary request generated by store.dispatch(loginToHost).

          // "if revoke host login failed (but not 401). just show error page of host login"
          // This is already accomplished as loginToHost.rejected updates the hostAuthErrors state,
          // which the Sidebar UI uses to show the "Connection Failed" / "Try Again" overlay.
          return Promise.reject(error);
        }
      } else {
        // Generic or system-level 401
        console.warn('Authentication expired. Redirecting to system login...');
        localStorage.removeItem('token');
        if (window.location.pathname !== '/login' && window.location.pathname !== '/register') {
          window.location.href = '/login';
        }
        return Promise.reject(error);
      }
    }

    // Standardize error messaging for components
    if (apiData) {
      apiData.message = apiData.data?.title || apiData.note || apiData.message || 'An unexpected error occurred';
    }

    return Promise.reject(error);
  }
);

export default apiClient;
